__all__ = ["basic_structures_definitions"]
from smart_scheduler_tools.basic_structures.basic_structures_definitions import Schedule
from smart_scheduler_tools.basic_structures.basic_structures_definitions import Subject